name: lab_3
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_svg: ^1.0.3
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.11
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.12
  image_picker: ^0.8.4+11
  flutter_keyboard_visibility: ^5.2.0
  carousel_slider: ^4.0.0
  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya.ttf
    - family: AlegreyaSans
      fonts:
        - asset: assets/fonts/AlegreyaSans.ttf